@startuml
package "Model"{
    enum GamePhase {
         START_TURN,
         IN_TURN,
         END_TURN,
         EVENT,
         END_GAME
    }
    enum Age{
        AGE_1
        AGE_2
        AGE_3
    }
    enum Tool {
        BREAD
        STONE
        BOAT
        RING
        ROPE
        BOWL
        STICK
        DOLL
        HOOK
        NECKLACE
    }
    enum TileId {
        START_1
        START_2
        START_3
        START_4
        LAST_TILE
        A
        B
        C
        D
        E
        F
        G
    }
    abstract class Card{
        -age : Age
        -id : string
        -minPlayers : int

        +getAge() : Age
        +setAge(age : Age) : boolean
        +getId() : string
        +setId(id : string) : boolean
        +getMinPlayers() : int
        +setMinPlayers(minPlayers : int) : boolean
    }
    class Artist extends Card{
    }
    class Gatherer extends Card{
    }
    class Event extends Card{
    }
    class Shaman extends Card{
        -stars : int

        +getStars() : int
        +setStars(stars : int) : boolean
    }
    class Builder extends Card{
        -discount : int
        -pp : int

        +getDiscount() : int
        +setDiscount(discount : int) : boolean
        +getPP() : int
        +setPP(pp : int) : boolean
    }
    class Inventor extends Card{
        -tool : Tool
        +getTool() : Tool
        +setTool(tool : Tool) : boolean
    }
    class Hunter extends Card{
        -food : boolean
        +hasFood() : boolean
        +setFood(food : boolean) : boolean
    }
    class Building extends Card{
        -foodCost : int
        -pp : int

        +getFoodCost() : int
        +setFoodCost(cost : int) : boolean
        +getPP() : int
        +setPP(pp : int) : boolean
    }
    class TileSet {
        -tiles : List<Tile>

        +getTile(id : TileId) : Tile
        +getTiles() : List<Tile>
    }
    class Tile {
        -tileId : TileId
        -isOccupied : boolean
        -occupier : Player
        -effectId : string
        -minPlayers : int

        +getId() : TileId
        +setId(id : TileId) : boolean
        +isOccupied() : boolean
        +getOccupier() : Player
        +getEffectId() : string
        +setEffectId(effectId : string) : boolean
        +getMinPlayers() : int
        +setMinPlayers(minPlayers : int) : boolean
        +occupy(p : Player) : boolean
        +deOccupy() : boolean
    }
    class Player {
        -id : int
        -nickname : string
        -cards : List<Card>
        -buildings : List<Building>
        -food : int
        -pp : int
        -isChoosing : boolean

        +getIsChoosing() : boolean
        +getId() : int
        +getFood() : int
        +getCards() : List<Card>
        +getBuildings() : List<Building>
        +getBuildingDiscount() : int
        +getStars() : int
        +getSustainmentDiscount() : int
        +getPP() : int
        +addCard(c : Card) : boolean
        +addBuilding(b : Building) : boolean
        +addFood(amount : int) : boolean
        +payFood(amount : int) : boolean
        +addPP (amount : int) : boolean
        +payPP(amount : int) : boolean
        +choose() : boolean
    }

    class GameState {
        -age : Age
        -turn : int
        -phase : GamePhase
        -players : List<Player>
        -deck : Deck
        -board : Board
        -currentPlayerIndex : int
        -turnOrder : List<Player>

        +getAge() : Age
        +getTurn() : int
        +getPhase() : GamePhase
        +getPlayer(index : int) : Player
        +setAge(age : Age) : boolean
        +setTurn(turn : int) : boolean
        +setPhase(phase : GamePhase) : boolean
        +getCurrentPlayer() : Player
        +getTurnOrder() : List<Player>
    }
    class Board {
        -tiles : TileSet
        -topCards : List<Card>
        -bottomCards : List<Card>
        -topBuildings : List<Building>
        -bottomBuildings : List<Building>

        +pickTopCard(index : int) : Card
        +pickBottomCard(index : int) : Card
        +pickTopBuilding(index : int) : Building
        +pickBottomBuilding(index : int) : Building
        +addTopCard(c : Card) : boolean
        +addBottomCard(c : Card) : boolean
        +addTopBuilding(b : Building) : boolean
        +discardBottomCards() : boolean
        +discardBottomBuildings() : boolean
        +topToBottomCards() : boolean
        +topToBottomBuildings() : boolean
    }
    class Deck {
        -age_1_Cards : List<Card>
        -age_2_Cards : List<Card>
        -age_3_Cards : List<Card>
        -age_1_Buildings : List<Building>
        -age_2_Buildings : List<Building>
        -age_3_Buildings : List<Building>

        +shuffle(age : Age) : boolean
        +popCard(age : Age) : Card
        +popBuilding(age : Age) : Building
    }

    GameState "1" *-- "1" Board
    GameState "1" *-- "1" Deck
    GameState "1" *-- "1..5" Player
    Board "1" *-- "1" TileSet
    TileSet "1" *-- "*" Tile
    Player "1" o-- "*" Card
    Player "1" o-- "*" Building
    Tile "*" o-- "0..1" Player : occupier
    Deck "1" *-- "*" Card
    Deck "1" *-- "*" Building
    Board "1" o-- "*" Card : top/bottom
    Board "1" o-- "*" Building : top/bottom
}
package "Controller"{
    interface ContextualEffect{
        +executeEffect(Player, GameState)
        +getTriggerPhase() : GamePhase
    }
    interface EventEffect {
        +executeEffect(List<Player>, state : GameState) : boolean
    }
    class BuildingsRegistry {
        -effects : HashMap<String, ContextualEffect>
        +BuildingsRegistry()
        +getEffect(id : string) : ContextualEffect
    }
    class EventRegistry {
        -events : HashMap<String, EventEffect>
        +EventRegistry()
        +getEffect(id : string) : EventEffect
    }
    class TileRegistry {
        -effects : Map<String, ContextualEffect>
        +TileRegistry()
        +getEffect(id : string) : ContextualEffect
    }

    class GameController {
        -state : GameState
        -buildingsRegistry : BuuildingsRegistry
        -eventRegistry : EventRegistry

        +createGame()
        +firstOrder()
        +triggerPhase()
        +nextPhase()
        +nextTurn()
        +nextAge()
    }

    GameController --> GameState : updates
    BuildingsRegistry --> ContextualEffect : manages
    EventRegistry --> EventEffect : manages
    TileRegistry --> ContextualEffect : manages
    GameController --> EventRegistry : uses
    GameController --> BuildingsRegistry : uses
    GameController -->TileRegistry : uses
}
@enduml